### PR TITLE
hw_8_exceptions

### PR DESCRIPTION
**Pull request by AlexG1987**
Please, check my code

### CODE REVIEW

**Comment by dd994** [comment]
The code works, perhaps it was better to do through try / catch, but it is on your choice

**Comment by anattoly** [comment]
I checked your code.
I think all your custom exceptions except the "OwnNullObjectException" can be "unchecked exeption"

**Comment by AlexG1987** [comment]
> I checked your code.
> I think all your custom exceptions except the "OwnNullObjectException" can be "unchecked exeption"

Why? Please, explain your opinion. In task description we need to throw exceptions, not print messages in console.

**Comment by AlexG1987** [comment]
> The code works, perhaps it was better to do through try / catch, but it is on your choice

Throw new works exactly like try\catch

**Comment by FuleiNataliya** [comment]
code working, all tasks are completed

**Comment by anattoly** [comment]
> > I checked your code.
> > I think all your custom exceptions except the "OwnNullObjectException" can be "unchecked exeption"
> 
> Why? Please, explain your opinion. In task description we need to throw exceptions, not print messages in console.

I had in mind the type of Exeption which you extends in custom exeptions change to type of "unchecked"

**Comment by AlexG1987** [comment]
> The code works, perhaps it was better to do through try / catch, but it is on your choice

I refactored my code on commit af3fa35 from throws on Main to try\catch for separate methods.
Thanks a lot.

**Comment by AlexG1987** [comment]
> > > I checked your code.
> > > I think all your custom exceptions except the "OwnNullObjectException" can be "unchecked exeption"
> > 
> > 
> > Why? Please, explain your opinion. In task description we need to throw exceptions, not print messages in console.
> 
> I had in mind the type of Exeption which you extendish in custom exeptions change to type of "unchecked"

Understood.
We will extend from the parent class, which will give us the extension of the narrowing?

**Comment by dd994** [comment]
everething good )

**Comment by anattoly** [comment]
Ready to move to support check.

**Pull request merged**
